kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./frontend/node_modules

  - name: frontend
    image: node:10.16.0
    commands:
      - cd frontend

  - name: docker-compose
    image: tiangolo/docker-with-compose
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      USERNAME:
        from_secret: username_hub
      PASSWORD:
        from_secret: password_hub
      ALLOWED_HOSTS:
        from_secret: allowed_hosts
      DATABASE_URL:
        from_secret: database_url
      SECRET_KEY:
        from_secret: secret_key
    commands:
      - docker login -u $USERNAME -p $PASSWORD
      - docker-compose build
      - docker-compose push
    when:
      branch:
        - master

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./frontend/node_modules

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      script:
        - /root/deploy-margo.sh
    when:
      branch: master

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
