version: "3"
services:
  margo-frontend:
    container_name: margo-frontend-container
    image: reryk/margo-frontend
    build: ./frontend
    restart: always
    env_file: .env.dev
    networks:
      - web
    ports:
      - "8001:80"
    depends_on:
      - margo-backend

  margo-database:
    container_name: margo-database-container
    image: postgres:9.4
    restart: always
    env_file: .env.dev
    volumes:
      - /opt/postgres/margo:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - 5432

  margo-backend:
    container_name: margo-backend-container
    image: reryk/margo-backend
    build: ./backend
    restart: always
#    command: bash -c "cd backend && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "cd backend && python manage.py runserver 0.0.0.0:8000"
    env_file: .env.dev
    volumes:
      - .:/code
      - '/opt/margo/static:/code/backend/static'
      - '/opt/margo/media:/code/backend/media'
    networks:
      - internal
      - web
    ports:
      - "8000:8000"
    depends_on:
      - margo-database

networks:
  web:
    external: true
  internal:
    external: false
