version: "3"
services:
  margo-frontend:
    container_name: margo-frontend-container
    image: reryk/margo-frontend
    build: ./frontend
    restart: always
    env_file: .env.prod
    environment:
      - VIRTUAL_HOST=margo.eryk.io
      - LETSENCRYPT_HOST=margo.eryk.io
      - LETSENCRYPT_EMAIL=erykruszczak@gmail.com
    volumes:
      - certs:/etc/nginx/certs:ro
      - media:/movie-media
    expose:
      - 80
      - 443
    depends_on:
      - margo-backend

  margo-backend:
    container_name: margo-backend-container
    image: reryk/margo-backend
    build: ./backend
    restart: always
    command: bash -c "python manage.py migrate && gunicorn margonem.wsgi -b 0.0.0.0:8000 --workers 2"
    env_file: .env.prod
    volumes:
      - media:/movie-media
    expose:
      - 8000
    depends_on:
      - margo-database

  margo-database:
    container_name: margo-database-container
    image: postgres:9.4
    restart: always
    env_file: .env.prod
    volumes:
      - /opt/postgres/margo:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  media:
  certs:
    external:
      name: nginx-proxy_certs

networks:
  default:
    external:
      name: nginx-proxy