version: "3"

services:
  moje-margo-frontend:
    container_name: moje-margo-frontend
    image: moje-margo-frontend
    restart: unless-stopped
    build: ./frontend
    volumes:
      - ./media:/margo-media
    ports:
      - '3000:80'
    expose:
      - 80
    depends_on:
      - moje-margo-backend

  moje-margo-backend:
    container_name: moje-margo-backend
    image: moje-margo-backend
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
#    command: bash -c "python manage.py migrate && gunicorn margonem.wsgi -b 0.0.0.0:8000 --workers 2"
    command: bash -c "gunicorn margonem.wsgi -b 0.0.0.0:8000 --workers 2"
    volumes:
      - ./media:/margo-media
    ports:
      - '8000:8000'
    expose:
      - 8000
    depends_on:
      - moje-margo-database

  moje-margo-database:
    container_name: moje-margo-database
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: postgres # required; superuser password
      POSTGRES_USER: postgres # superuser to be created
      POSTGRES_DB: db # database to be created
    restart: unless-stopped
    volumes:
      - moje-margo_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432


volumes:
  moje-margo_data:
    external: true
