version: "3"
services:
  margo-frontend:
    container_name: margo-frontend-container
    image: reryk/margo-frontend
    build: ./frontend
    restart: always
    env_file: .env.prod
    networks:
      - web
    ports:
      - "8001:80"
    depends_on:
      - margo-backend

  margo-database:
    container_name: margo-database-container
    image: postgres:9.4
    restart: always
    env_file: .env.prod
    volumes:
      - '/opt/postgres/margo:/var/lib/postgresql/data'
    networks:
      - internal
    expose:
      - 5432

  margo-backend:
    container_name: margo-backend-container
    build: ./backend
    restart: always
    env_file: .env.prod
    command: bash -c "cd backend && python manage.py collectstatic --noinput && gunicorn margonem.wsgi -b 0.0.0.0:8000 --workers 1"
    volumes:
      - '.:/code'
      - '/opt/margo:/opt/margo'
    networks:
      - internal
      - web
    ports:
      - '8000:8000'
    depends_on:
      - margo-database

networks:
  web:
    external: true
  internal:
    external: false
