# Generated by Django 2.0.2 on 2018-02-12 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180211_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dodano'),
            preserve_default=False,
        ),
    ]
