# Generated by Django 2.0.2 on 2018-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180212_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='opis',
        ),
        migrations.AddField(
            model_name='item',
            name='same_stats',
            field=models.CharField(blank=True, max_length=255, verbose_name='The same stats'),
        ),
    ]
