# Generated by Django 2.0.2 on 2018-02-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20180213_1426'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['slug'], name='items_item_slug_d94d1c_idx'),
        ),
    ]
