# Generated by Django 2.0.2 on 2018-02-12 09:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Statystyki'),
        ),
    ]
