# Generated by Django 2.0.2 on 2018-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20180214_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='npc_expbon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zwieksza ilosc expa za potwory'),
        ),
    ]
