# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_stats', models.CharField(blank=True, max_length=300, null=True)),
                ('lvl', models.PositiveIntegerField(blank=True, null=True)),
                ('bag', models.PositiveIntegerField(blank=True, null=True)),
                ('hidden_stats', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('img_url', models.URLField(max_length=255)),
                ('lowcrit', models.PositiveIntegerField(blank=True, null=True)),
                ('crit', models.PositiveIntegerField(blank=True, null=True)),
                ('critval', models.PositiveIntegerField(blank=True, null=True)),
                ('critmval', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('hpbon', models.FloatField(blank=True, null=True, verbose_name='pkt zycia za hp')),
                ('heal', models.PositiveIntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='zycie')),
                ('ds', models.IntegerField(blank=True, null=True, verbose_name='sila')),
                ('dz', models.IntegerField(blank=True, null=True, verbose_name='zrecznosc')),
                ('di', models.IntegerField(blank=True, null=True, verbose_name='inteligencja')),
                ('da', models.IntegerField(blank=True, null=True)),
                ('ac', models.PositiveIntegerField(blank=True, null=True)),
                ('pierceb', models.PositiveIntegerField(blank=True, null=True)),
                ('adest', models.PositiveIntegerField(blank=True, null=True)),
                ('blok', models.IntegerField(blank=True, null=True)),
                ('absorbm', models.PositiveIntegerField(blank=True, null=True)),
                ('absorb', models.PositiveIntegerField(blank=True, null=True)),
                ('slow', models.FloatField(blank=True, null=True, verbose_name='obniza sa')),
                ('sa', models.IntegerField(blank=True, null=True, verbose_name='szybkosc ataku')),
                ('evade', models.IntegerField(blank=True, null=True, verbose_name='unik')),
                ('lowevade', models.PositiveIntegerField(blank=True, null=True)),
                ('acdmg', models.PositiveIntegerField(blank=True, null=True)),
                ('dmg', models.CharField(blank=True, max_length=20, null=True)),
                ('light', models.CharField(blank=True, max_length=20, null=True)),
                ('fire', models.PositiveIntegerField(blank=True, null=True)),
                ('frost', models.PositiveIntegerField(blank=True, null=True)),
                ('frost_slowed', models.FloatField(blank=True, null=True)),
                ('endest', models.PositiveIntegerField(blank=True, null=True)),
                ('manadest', models.PositiveIntegerField(blank=True, null=True)),
                ('manabon', models.PositiveIntegerField(blank=True, null=True)),
                ('energybon', models.PositiveIntegerField(blank=True, null=True)),
                ('resfire', models.IntegerField(blank=True, null=True)),
                ('reslight', models.IntegerField(blank=True, null=True)),
                ('resfrost', models.IntegerField(blank=True, null=True)),
                ('act', models.IntegerField(blank=True, null=True)),
                ('resdmg', models.PositiveIntegerField(blank=True, null=True)),
                ('leczy', models.PositiveIntegerField(blank=True, null=True)),
                ('pierce', models.PositiveIntegerField(blank=True, null=True)),
                ('upg', models.PositiveIntegerField(blank=True, null=True)),
                ('ttl', models.PositiveIntegerField(blank=True, null=True)),
                ('abdest', models.PositiveIntegerField(blank=True, null=True)),
                ('contra', models.PositiveIntegerField(blank=True, null=True)),
                ('ammo', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('gold', models.PositiveIntegerField(blank=True, null=True)),
                ('respred', models.PositiveIntegerField(blank=True, null=True)),
                ('pdmg', models.PositiveIntegerField(blank=True, null=True)),
                ('fullheal', models.PositiveIntegerField(blank=True, null=True)),
                ('lowreq', models.PositiveIntegerField(blank=True, null=True)),
                ('runes', models.PositiveIntegerField(blank=True, null=True)),
                ('btype', models.PositiveIntegerField(blank=True, null=True)),
                ('timelimit', models.PositiveIntegerField(blank=True, null=True)),
                ('poison', models.PositiveIntegerField(blank=True, null=True)),
                ('poison_slowed', models.FloatField(blank=True, null=True)),
                ('wound', models.PositiveIntegerField(blank=True, null=True)),
                ('wound_chance', models.FloatField(blank=True, null=True)),
                ('afterheal', models.PositiveIntegerField(blank=True, null=True)),
                ('afterheal_chance', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='legbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemBonus'),
        ),
        migrations.AddField(
            model_name='item',
            name='profession',
            field=models.ManyToManyField(to='items.Profession'),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemRarity'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemType'),
        ),
    ]
