# Generated by Django 2.0.2 on 2018-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reqp',
            field=models.CharField(blank=True, max_length=6, verbose_name='Wymagane profesje'),
        ),
    ]
