# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170507_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Czas odnowienia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='abdest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niszczenie absorpcji przed atakiem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='absorb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Absorpcje fizyczne'),
        ),
        migrations.AlterField(
            model_name='item',
            name='absorbm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Absorpcje magiczne'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ac',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pancerz'),
        ),
        migrations.AlterField(
            model_name='item',
            name='acdmg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niszczenie punktów pancerza podczas ciosu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='act',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odporność na truciznę'),
        ),
        migrations.AlterField(
            model_name='item',
            name='adest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niszczenie energii'),
        ),
        migrations.AlterField(
            model_name='item',
            name='afterheal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wyleczenie po walce, obrażenia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='afterheal_chance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wyleczenie po walce, szanse'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ammo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bag',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Miejsc na przedmioty'),
        ),
        migrations.AlterField(
            model_name='item',
            name='blok',
            field=models.IntegerField(blank=True, null=True, verbose_name='Blok'),
        ),
        migrations.AlterField(
            model_name='item',
            name='btype',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='??? btype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimum sztuk razem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contra',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Szanse na kontrę po krytyku'),
        ),
        migrations.AlterField(
            model_name='item',
            name='crit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cios krytyczny'),
        ),
        migrations.AlterField(
            model_name='item',
            name='critmval',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Siła krytyka magicznego'),
        ),
        migrations.AlterField(
            model_name='item',
            name='critval',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Siła krytyka fizycznego'),
        ),
        migrations.AlterField(
            model_name='item',
            name='da',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wszystkie cechy'),
        ),
        migrations.AlterField(
            model_name='item',
            name='di',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inteligencja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dmg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Atak'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siła'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zręczność'),
        ),
        migrations.AlterField(
            model_name='item',
            name='endest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niszczenie energii'),
        ),
        migrations.AlterField(
            model_name='item',
            name='energybon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Energia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='evade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unik'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fire',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obrażenia od ognia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='frost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obrażenia od zimna'),
        ),
        migrations.AlterField(
            model_name='item',
            name='frost_slowed',
            field=models.FloatField(blank=True, null=True, verbose_name='spowalnia cel od zimna'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fullheal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pełne leczenie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Złoto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='heal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Przywraca punktów życia podczas walki'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hidden_stats',
            field=models.BooleanField(default=False, verbose_name='Niezidentyfikowany'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Życie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hpbon',
            field=models.FloatField(blank=True, null=True, verbose_name='Punkty życia za punkt hp'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Grafika'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.URLField(max_length=255, verbose_name='Źródło grafiki'),
        ),
        migrations.AlterField(
            model_name='item',
            name='json_stats',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Statystyki w kolejności'),
        ),
        migrations.AlterField(
            model_name='item',
            name='leczy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Leczy punktów życia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='legbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemBonus', verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='light',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Obrażenia od błyskawic'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lowcrit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Podczas obrony szansa na cios krytyczny przeciwnika jest mniejsza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lowevade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Podczas ataku unik przeciwnika jest mniejszy'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lowreq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zmniejszone wymagania lvl'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lvl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lvl'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manabon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mana'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manadest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niszczenie many'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='opis',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pdmg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Atak fizyczny'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pierce',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Przebicie pancerza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pierceb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Szanse na zablokowanie przebicia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='poison',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obrażenia od trucizny'),
        ),
        migrations.AlterField(
            model_name='item',
            name='poison_slowed',
            field=models.FloatField(blank=True, null=True, verbose_name='spowolnia cel od trucizny'),
        ),
        migrations.AlterField(
            model_name='item',
            name='profession',
            field=models.ManyToManyField(to='items.Profession', verbose_name='Profesje'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemRarity', verbose_name='Rzadkość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='resdmg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obniżenie odporności podczas ataku'),
        ),
        migrations.AlterField(
            model_name='item',
            name='resfire',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odporność na ogień'),
        ),
        migrations.AlterField(
            model_name='item',
            name='resfrost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odporność na zimno'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reslight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odporność na błyskawice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='respred',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Przyśpiesza wracanie do siebie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='runes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dodaje smoczych run'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sa',
            field=models.IntegerField(blank=True, null=True, verbose_name='SA'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slow',
            field=models.FloatField(blank=True, null=True, verbose_name='Obniża SA przeciwnika'),
        ),
        migrations.AlterField(
            model_name='item',
            name='timelimit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Można używać co'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zniknie za .. minut'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemType', verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ulepszenie procentowe'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wound',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Głęboka rana, szanse'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wound_chance',
            field=models.FloatField(blank=True, null=True, verbose_name='Głęboka rana, obrażenia'),
        ),
    ]
