# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20170510_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='leczy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leczy punktów życia'),
        ),
    ]
