# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20170510_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='perheal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leczy % życia'),
        ),
    ]
