# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_perheal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='action',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Special action'),
        ),
    ]
