# Generated by Django 2.0.2 on 2018-02-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180212_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lvl',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Lvl'),
        ),
    ]
