# Generated by Django 2.0.2 on 2018-02-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20180213_1410'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['lvl'], name='items_item_lvl_a9911b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='items_item_type_730087_idx'),
        ),
    ]
