# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20170510_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lowheal2turns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Obniżenie leczenia turowego przeciwnika na 2 tury'),
        ),
    ]
