# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20170510_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='resmanaendest_ene',
        ),
        migrations.RemoveField(
            model_name='item',
            name='resmanaendest_mana',
        ),
        migrations.AddField(
            model_name='item',
            name='worth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wartość'),
        ),
    ]
