# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20170511_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resacdmg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ochrona przed niszczeniem pancerza'),
        ),
        migrations.AddField(
            model_name='item',
            name='resmanaendest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obniżanie niszczenia many'),
        ),
        migrations.AddField(
            model_name='item',
            name='resmanaendest_ene',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obniżanie niszczenia energii'),
        ),
        migrations.AlterField(
            model_name='item',
            name='worth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartość'),
        ),
    ]
