# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20170511_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lowcritallval',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obniżenie mocy krytyka fizycznego i magicznego'),
        ),
    ]
