# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_lowcritallval'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='npc_lootbon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Special stat'),
        ),
    ]
