# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_npc_lootbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creditsbon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dodaje smoczych łusek'),
        ),
    ]
