# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_item_creditsbon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='critmval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siła krytyka magicznego'),
        ),
        migrations.AlterField(
            model_name='item',
            name='critval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siła krytyka fizycznego'),
        ),
    ]
