# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20170512_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='adest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zadaje obrażenia właścicielowi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ilość (Nie można dzielić)'),
        ),
    ]
