# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20170512_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lowreq',
        )
    ]
