# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20170517_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='json_stats',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Statystyki w kolejności'),
        ),
    ]
