# Generated by Django 2.0.2 on 2018-02-07 08:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20180207_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', verbose_name='Statystyki w kolejności'),
        ),
    ]
