# Generated by Django 2.0.2 on 2018-02-07 08:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20180207_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Statystyki w kolejności'),
        ),
    ]
