name: Push Docker Image

on:
  push:
    branches: [ master ]


env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}/
  DOCKER_CLIENT_TIMEOUT: 180
  COMPOSE_HTTP_TIMEOUT: 180


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build a frontend image
        run: docker buildx build \
              -t ${{ secrets.DOCKER_REGISTRY }}/moje-margo-frontend:latest \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              frontend/

#      - name: Push images
#        run: docker-compose push