name: Push Docker Image

on:
  push:
    branches: [ master ]


env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}/
  DOCKER_CLIENT_TIMEOUT: 180
  COMPOSE_HTTP_TIMEOUT: 180
  PYTHON_VERSION: '3.6'
  NODE_VERSION: '10'


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Python version
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}



      - name: Install
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build



      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt



      - name: Build & Push a frontend image
        working-directory: ./frontend
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKER_REGISTRY }}/moje-margo-frontend:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            -f Dockerfile2 .

      - name: Build & Push a backend image
        working-directory: ./backend
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKER_REGISTRY }}/moje-margo-backend:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            -f Dockerfile2 .