name: Push Docker Image

on:
  push:
    branches: [ master ]


env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}/
  DOCKER_CLIENT_TIMEOUT: 180
  COMPOSE_HTTP_TIMEOUT: 180
  PYTHON_VERSION: '3.6'
  NODE_VERSION: '10'


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Build a frontend image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/moje-margo-frontend:latest -f Dockerfile2 .

      - name: Build a backend image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/moje-margo-backend:latest .

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/moje-margo-backend:latest &&
          docker push ${{ secrets.DOCKER_REGISTRY }}/moje-margo-frontend:latest
