name: Push Docker Image

on:
  push:
    branches: [ master ]


env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}/
  DOCKER_CLIENT_TIMEOUT: 180
  COMPOSE_HTTP_TIMEOUT: 180


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Build images
      run: docker-compose build
      
    - name: Push images
      run: docker-compose push