name: Release

on:
  workflow_dispatch


env:
  BACKEND_IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/moje-margo-backend
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/moje-margo-frontend


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Build a frontend image
        working-directory: ./frontend
        run: |
          docker build --tag ${{ env.FRONTEND_IMAGE_NAME }}:latest .

      - name: Build a backend image
        working-directory: ./backend
        run: |
          docker build --tag ${{ env.BACKEND_IMAGE_NAME }}:latest .

      - name: Push
        run: |
          docker push ${{ env.FRONTEND_IMAGE_NAME }}:latest
          docker push ${{ env.BACKEND_IMAGE_NAME }}:latest
